### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ricePak** [Ayden1456/ramv4#2]
#### Description

As the entry point of your repository, `README.md` **NEEDS** to be fancy to show your pro-ness. Being fancy doesn't need to use cool stuff - just to follow some good old conventions. Start learning the conventions now can be really helpful as most companies _DO_ require their programmers to do proper `README.md` and proper issues (like this).

#### Procedure

- [x] To start, follow [this](https://github.com/RichardLitt/standard-readme) guide on writing proper READMEs.
- [x] Also read [this](https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md) for proper issues. Your unsolved problems can be posted as issues, so you can have a good understanding of your tasks, or just label them and leave them to someone else (like Steebs). You can also sort them by grouping them by labels (`bug`, `enhancement`, `question`, etc.).
- [x] Good luck! 

#### Homework check

Tell me or close this issue whenever your README.md is nice and pro.

**Comment by Ayden1456** [comment]
Cool, thanks Steebs
